version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: glpi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - glpi_data:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    container_name: glpi_app
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpi
      - MYSQL_DATABASE=glpidb
    depends_on:
      - db
    volumes:
      - glpi_app_data:/var/www/html

volumes:
  glpi_data:
  glpi_app_data: